// Code generated by "stringer -type=TransformationCacheSort"; DO NOT EDIT.

package formula

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransNNF-0]
	_ = x[TransCNFFactorization-1]
	_ = x[TransDNFFactorization-2]
	_ = x[TransAIG-3]
	_ = x[TransDistrSimpl-4]
	_ = x[TransUnitPropagation-5]
	_ = x[TransBDDCNF-6]
	_ = x[TransBDDNF-7]
}

const _TransformationCacheSort_name = "TransNNFTransCNFFactorizationTransDNFFactorizationTransAIGTransDistrSimplTransUnitPropagationTransBDDCNFTransBDDNF"

var _TransformationCacheSort_index = [...]uint8{0, 8, 29, 50, 58, 73, 93, 104, 114}

func (i TransformationCacheSort) String() string {
	if i >= TransformationCacheSort(len(_TransformationCacheSort_index)-1) {
		return "TransformationCacheSort(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransformationCacheSort_name[_TransformationCacheSort_index[i]:_TransformationCacheSort_index[i+1]]
}
