// Code generated by "stringer -type=Tristate"; DO NOT EDIT.

package formula

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TristateTrue-0]
	_ = x[TristateFalse-1]
	_ = x[TristateUndef-2]
}

const _Tristate_name = "TRUEFALSEUNDEF"

var _Tristate_index = [...]uint8{0, 4, 9, 14}

func (i Tristate) String() string {
	if i >= Tristate(len(_Tristate_index)-1) {
		return "Tristate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tristate_name[_Tristate_index[i]:_Tristate_index[i+1]]
}
