// Code generated by "stringer -type=ReorderingMethod"; DO NOT EDIT.

package bdd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReorderNone-0]
	_ = x[ReorderWin2-1]
	_ = x[ReorderWin2Ite-2]
	_ = x[ReorderSift-3]
	_ = x[ReorderSiftIte-4]
	_ = x[ReorderWin3-5]
	_ = x[ReorderWin3Ite-6]
	_ = x[ReorderRandom-7]
}

const _ReorderingMethod_name = "ReorderNoneReorderWin2ReorderWin2IteReorderSiftReorderSiftIteReorderWin3ReorderWin3IteReorderRandom"

var _ReorderingMethod_index = [...]uint8{0, 11, 22, 36, 47, 61, 72, 86, 99}

func (i ReorderingMethod) String() string {
	if i >= ReorderingMethod(len(_ReorderingMethod_index)-1) {
		return "ReorderingMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReorderingMethod_name[_ReorderingMethod_index[i]:_ReorderingMethod_index[i+1]]
}
