// Code generated by "stringer -type=ClauseMinimization"; DO NOT EDIT.

package sat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClauseMinNone-0]
	_ = x[ClauseMinBasic-1]
	_ = x[ClauseMinDeep-2]
}

const _ClauseMinimization_name = "ClauseMinNoneClauseMinBasicClauseMinDeep"

var _ClauseMinimization_index = [...]uint8{0, 13, 27, 40}

func (i ClauseMinimization) String() string {
	if i >= ClauseMinimization(len(_ClauseMinimization_index)-1) {
		return "ClauseMinimization(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClauseMinimization_name[_ClauseMinimization_index[i]:_ClauseMinimization_index[i+1]]
}
