// Code generated by "stringer -type=Algorithm"; DO NOT EDIT.

package maxsat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlgWBO-0]
	_ = x[AlgIncWBO-1]
	_ = x[AlgLinearSU-2]
	_ = x[AlgLinearUS-3]
	_ = x[AlgMSU3-4]
	_ = x[AlgWMSU3-5]
	_ = x[AlgOLL-6]
}

const _Algorithm_name = "AlgWBOAlgIncWBOAlgLinearSUAlgLinearUSAlgMSU3AlgWMSU3AlgOLL"

var _Algorithm_index = [...]uint8{0, 6, 15, 26, 37, 44, 52, 58}

func (i Algorithm) String() string {
	if i >= Algorithm(len(_Algorithm_index)-1) {
		return "Algorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Algorithm_name[_Algorithm_index[i]:_Algorithm_index[i+1]]
}
