// Code generated by "stringer -type=problemType"; DO NOT EDIT.

package maxsat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unweighted-0]
	_ = x[weighted-1]
}

const _problemType_name = "unweightedweighted"

var _problemType_index = [...]uint8{0, 10, 18}

func (i problemType) String() string {
	if i >= problemType(len(_problemType_index)-1) {
		return "problemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _problemType_name[_problemType_index[i]:_problemType_index[i+1]]
}
