// Code generated by "stringer -type=WeightStrategy"; DO NOT EDIT.

package maxsat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeightNone-0]
	_ = x[WeightNormal-1]
	_ = x[WeightDiversify-2]
}

const _WeightStrategy_name = "WeightNoneWeightNormalWeightDiversify"

var _WeightStrategy_index = [...]uint8{0, 10, 22, 37}

func (i WeightStrategy) String() string {
	if i >= WeightStrategy(len(_WeightStrategy_index)-1) {
		return "WeightStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeightStrategy_name[_WeightStrategy_index[i]:_WeightStrategy_index[i+1]]
}
