// Code generated by "stringer -type=ALKEncoder"; DO NOT EDIT.

package encoding

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ALKTotalizer-0]
	_ = x[ALKModularTotalizer-1]
	_ = x[ALKCardinalityNetwork-2]
	_ = x[ALKBest-3]
}

const _ALKEncoder_name = "ALKTotalizerALKModularTotalizerALKCardinalityNetworkALKBest"

var _ALKEncoder_index = [...]uint8{0, 12, 31, 52, 59}

func (i ALKEncoder) String() string {
	if i >= ALKEncoder(len(_ALKEncoder_index)-1) {
		return "ALKEncoder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ALKEncoder_name[_ALKEncoder_index[i]:_ALKEncoder_index[i+1]]
}
