// Code generated by "stringer -type=AMKEncoder"; DO NOT EDIT.

package encoding

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AMKTotalizer-0]
	_ = x[AMKModularTotalizer-1]
	_ = x[AMKCardinalityNetwork-2]
	_ = x[AMKBest-3]
}

const _AMKEncoder_name = "AMKTotalizerAMKModularTotalizerAMKCardinalityNetworkAMKBest"

var _AMKEncoder_index = [...]uint8{0, 12, 31, 52, 59}

func (i AMKEncoder) String() string {
	if i >= AMKEncoder(len(_AMKEncoder_index)-1) {
		return "AMKEncoder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AMKEncoder_name[_AMKEncoder_index[i]:_AMKEncoder_index[i+1]]
}
