// Code generated by "stringer -type=AMOEncoder"; DO NOT EDIT.

package encoding

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AMOPure-0]
	_ = x[AMOLadder-1]
	_ = x[AMOProduct-2]
	_ = x[AMONested-3]
	_ = x[AMOCommander-4]
	_ = x[AMOBinary-5]
	_ = x[AMOBimander-6]
	_ = x[AMOBest-7]
}

const _AMOEncoder_name = "AMOPureAMOLadderAMOProductAMONestedAMOCommanderAMOBinaryAMOBimanderAMOBest"

var _AMOEncoder_index = [...]uint8{0, 7, 16, 26, 35, 47, 56, 67, 74}

func (i AMOEncoder) String() string {
	if i >= AMOEncoder(len(_AMOEncoder_index)-1) {
		return "AMOEncoder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AMOEncoder_name[_AMOEncoder_index[i]:_AMOEncoder_index[i+1]]
}
