// Code generated by "stringer -type=BimanderGroupSize"; DO NOT EDIT.

package encoding

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BimanderHalf-0]
	_ = x[BimanderSqrt-1]
	_ = x[BimanderFixed-2]
}

const _BimanderGroupSize_name = "BimanderHalfBimanderSqrtBimanderFixed"

var _BimanderGroupSize_index = [...]uint8{0, 12, 24, 37}

func (i BimanderGroupSize) String() string {
	if i >= BimanderGroupSize(len(_BimanderGroupSize_index)-1) {
		return "BimanderGroupSize(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BimanderGroupSize_name[_BimanderGroupSize_index[i]:_BimanderGroupSize_index[i+1]]
}
