// Code generated by "stringer -type=EXKEncoder"; DO NOT EDIT.

package encoding

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EXKTotalizer-0]
	_ = x[EXKCardinalityNetwork-1]
	_ = x[EXKBest-2]
}

const _EXKEncoder_name = "EXKTotalizerEXKCardinalityNetworkEXKBest"

var _EXKEncoder_index = [...]uint8{0, 12, 33, 40}

func (i EXKEncoder) String() string {
	if i >= EXKEncoder(len(_EXKEncoder_index)-1) {
		return "EXKEncoder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EXKEncoder_name[_EXKEncoder_index[i]:_EXKEncoder_index[i+1]]
}
